git_user_name: "DKANomad"
op_git_email: "op://Personal/Git Config/email"

dotfiles_roles:
  - name: ssh
    profiles: [personal, work]
  - name: alacritty
    profiles: [personal, work]
  - name: burpsuite
    profiles: [personal]
  - name: fzf
    profiles: [personal, work]
  - name: k9s
    profiles: [personal, work]
  - name: lazygit
    profiles: [personal, work]
  - name: nvm
    profiles: [personal, work]
  - name: podman
    profiles: [personal]
  - name: pwsh
    profiles: [personal, work]
  - name: tmux
    profiles: [personal, work]
  - name: zsh
    profiles: [personal, work]
  - name: golang
    profiles: [personal, work]
  - name: elixir
    profiles: [personal, work]
  - name: ghostty
    profiles: [personal, work]
  - name: claude-code
    profiles: [personal]
  - name: cursor
    profiles: [personal]

ssh_keys:
  - name: id_ed25519
    profiles: [personal]
    op_private_key: "op://Personal/SSH Key/private key"
    op_public_key: "op://Personal/SSH Key/public key"
