---
- name: Rust | Install rust via curl
  block:
    - name: Rust | Check if rustup is installed
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.cargo/bin/rustup"
      register: rust_rustup_installed

    - name: Rust | Install rustup
      ansible.builtin.shell: >
        set -o pipefail && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"
        executable: /bin/bash
      when: not rust_rustup_installed.stat.exists

    - name: Rust | Add cargo bin to PATH in shell profile
      ansible.builtin.lineinfile: # noqa: risky-file-permissions
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'export PATH="$HOME/.cargo/bin:$PATH"'
        create: true
      when: not rust_rustup_installed.stat.exists
