---
- name: "ZSH | Install oh-my-posh"
  community.general.homebrew:
    name: jandedobbeleer/oh-my-posh/oh-my-posh
    state: present

- name: "ZSH | Copy .zprofile"
  ansible.builtin.template:
    src: ".zprofile.j2"
    dest: "{{ ansible_user_dir }}/.zprofile"
    mode: "0644"