---
- name: "Bash | Detect oh-my-posh"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.ohmyposh"
  register: ohmyposh

- name: "ZSH | Register oh-my-posh state"
  ansible.builtin.set_fact:
    ohmyposh_is_installed: "{{ ohmyposh.stat.exists }}"

- name: "ZSH | Debug oh-my-posh is installed"
  ansible.builtin.debug:
    var: ohmyposh_is_installed

- name: "Run mac tasks"
  ansible.builtin.import_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: "ZSH | Copy .zprofile"
  ansible.builtin.copy:
    src: ".zprofile"
    dest: "{{ ansible_user_dir }}/.zprofile"
    mode: "0644"