[shell]
program = "/bin/zsh"
args = ["--login", "-c", "tmux a || tmux new -s main"]

[font]
normal = { family = "FiraMono Nerd Font", style = "Regular" }
bold = { family = "FiraMono Nerd Font", style = "Bold" }

[keyboard]
bindings = [
    { key = "Space", mods = "Control", chars = "\u0000" }
]

[window]
startup_mode = "Maximized"