---
- name: "Ghostty | Install using brew"
  community.general.homebrew_cask:
    name: ghostty

- name: "Ghostty | Copy config file"
  block:
    - name: Ensure config dir exists
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/ghostty"
        state: directory
        mode: "0755"

    - name: Copy ghostty config
      ansible.builtin.copy:
        src: config
        dest: "{{ ansible_user_dir }}/.config/ghostty/config"
        mode: "0644"

    - name: Copy ghostty start script
      ansible.builtin.copy:
        src: tmux_ghostty.sh
        dest: "{{ ansible_user_dir }}/.config/ghostty/tmux_ghostty.sh"
        mode: "0764"
