---
- name: Install Powershell
  ansible.builtin.include_role:
    name: winget
  vars:
    winget_packages:
      - Microsoft.PowerShell

- name: Powershell | Install modules
  ansible.builtin.shell: |
    if(-not (Get-Module -ListAvailable -Name Terminal-Icons)) {
      Install-Module -Name Terminal-Icons -Repository PSGallery
    }

    if(-not (Get-Module -ListAvailable -Name PSReadLine)) {
      Install-Module PSReadLine -AllowPrerelease -Force
    }

    if(-not (Get-Module -ListAvailable -Name z)) {
      Install-Module -Name z
    }
  args:
    executable: pwsh.exe

- name: Powershell | Copy profile
  ansible.builtin.copy:
    src: profile
    dest: "/mnt/c/Users/{{ wsl_host_user }}/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
    force: true
  