---
- name: "Alacritty | Install with homebrew"
  community.general.homebrew:
    name: alacritty
    
- name: "Alacritty | Copy config file"
  ansible.builtin.copy:
    src: alacritty.toml
    dest: "{{ ansible_user_dir }}/.config/alacritty.toml"
    mode: "0644"