---
- name: Install Alacritty
  ansible.builtin.include_role:
    name: winget
  vars:
    winget_packages:
      - Alacritty.Alacritty

- name: Copy Alacritty config into Windows
  block:
    - name: Check to see if AppData\Roaming\alacritty exists
      ansible.builtin.stat:
        path: /mnt/c/Users/{{ wsl_host_user }}/AppData/Roaming/alacritty
      register: alacritty_dir

    - name: Ensure AppData\Roaming\alacritty exists
      ansible.builtin.shell:
        cmd: New-Item -ItemType Directory -Path "$env:APPDATA\alacritty" -ErrorAction SilentlyContinue
      failed_when: false
      args:
        executable: powershell.exe
      when: not alacritty_dir.stat.exists

    - name: Copy Alacritty config
      ansible.builtin.template:
        src: alacritty_wsl.toml.j2
        dest: /mnt/c/Users/{{ wsl_host_user }}/AppData/Roaming/alacritty/alacritty.toml
        mode: "0644"
